services:
  panel:
    image: ghcr.io/itsmeares/better-zcp:latest
    build:
      context: .
      args:
        UID: ${PUID:-1000}
        GID: ${PGID:-1000}
    container_name: zomboid-panel
    restart: unless-stopped
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - panel-data:/app/data
      - panel-logs:/app/logs

    environment:
      - NODE_ENV=production
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PANEL_DOCKER_CONTROL_ENABLED=${PANEL_DOCKER_CONTROL_ENABLED:-false}
      - TRUST_PROXY=${TRUST_PROXY:-false}

volumes:
  panel-data:
  panel-logs:
