packages:
  - apps/*

overrides:
  js-yaml@^4.1.1: 4.3.2
  vite@*: "catalog:"

allowBuilds:
  cpu-features: true
  esbuild: true
  ssh2: true

minimumReleaseAgeExclude:
  - "@tanstack/history@1.162.2"
  - "@tanstack/react-router@1.170.33"
  - "@tanstack/router-core@1.171.28"
  - "@tanstack/router-generator@1.167.34"
  - "@tanstack/router-plugin@1.168.36"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.0
  vite-plus: 1.0.0-rc.0
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
