import { describe, expect, it } from "vitest";
import { VALID_ACTIONS } from "../routes/panelBridge.ts";

const PINNED_VALID_ACTIONS = [
  "ping",
  "getServerInfo",
  "getWeather",
  "getGameTime",
  "getWorldStats",
  "getPlayerDetails",
  "getAllPlayerDetails",
  "healPlayer",
  "killPlayer",
  "teleportPlayer",
  "setGodMode",
  "setInvisible",
  "setNoclip",
  "giveItem",
  "exportPlayerData",
  "importPlayerData",
  "triggerBlizzard",
  "triggerTropicalStorm",
  "triggerStorm",
  "stopWeather",
  "startRain",
  "stopRain",
  "setSnow",
  "generateWeather",
  "setTemperature",
  "setWind",
  "setFog",
  "setClouds",
  "setDayLight",
  "setNightStrength",
  "setDesaturation",
  "setViewDistance",
  "setAmbient",
  "setClimateFloat",
  "resetClimateOverrides",
  "getClimateFloats",
  "setGameTime",
  "triggerLightning",
  "playWorldSound",
  "playSoundNearPlayer",
  "triggerGunshot",
  "triggerAlarmSound",
  "createNoise",
  "sendToServerChat",
  "getUtilitiesStatus",
  "restoreUtilities",
  "shutOffUtilities",
  "saveWorld",
  "getSandboxOptions",
  "getAllSandboxOptions",
  "setSandboxOption",
  "getZombieCount",
  "clearZombiesNearPlayer",
  "clearAllZombies",
  "spawnHordeNearPlayer",
  "spawnHordeBehindPlayer",
  "airdrop",
  "getSafehouses",
  "safehouseAddPlayer",
  "safehouseRemovePlayer",
  "safehouseSetOwner",
  "safehouseSetRespawn",
  "getFactions",
  "createFaction",
  "factionAddPlayer",
  "factionRemovePlayer",
  "factionSetTag",
  "removeFaction",
  "getVehiclesDetailed",
  "vehicleRepair",
  "vehicleSetAlarm",
  "vehicleSetSiren",
  "vehicleSetTrunkLocked",
  "vehicleSetFuel",
  "vehicleSetBattery",
  "removeVehicle",
  "removeVehiclesInArea",
  "spawnVehicleAt",
  "vehicleHotwire",
  "getTimeSpeed",
  "setTimeSpeed",
  "triggerHelicopterEvent",
  "stopHelicopterEvent",
  "triggerSwarmEvent",
  "runEventSequence",
  "getInfrastructureSnapshot",
  "moderationKickUser",
  "moderationBanUser",
  "moderationBanIP",
  "moderationBanSteamID",
  "getDebugLog",
  "setDebugMode",
  "getStats",
  "checkAPI",
  "getAvailableHandlers",
  "clearErrors",
  "getItemCatalog",
  "getVehicleCatalog",
  // Added 2026-08-29 (pin-literal-sendcommand-strings-against-valid-actions):
  // debugItemScript was a real gap, not a false alarm -- POST /catalog/
  // debug-item-script has called sendCommand("debugItemScript", {}) since
  // that route existed, and PanelBridge.lua genuinely implements the
  // handler; it was simply never added here.
  "debugItemScript",
];

describe("panelBridge.js VALID_ACTIONS drift gate", () => {
  it("keeps the HTTP allowlist aligned with implemented bridge commands", () => {
    const current = [...VALID_ACTIONS].sort();
    const pinned = [...PINNED_VALID_ACTIONS].sort();

    expect(
      current,
      current.length !== pinned.length
        ? `VALID_ACTIONS now has ${current.length} entries, pin expects ${pinned.length}. ` +
            `Added: ${current.filter((a) => !pinned.includes(a)).join(", ") || "(none)"}. ` +
            `Removed: ${pinned.filter((a) => !current.includes(a)).join(", ") || "(none)"}.`
        : "VALID_ACTIONS membership changed without the pin being updated.",
    ).toEqual(pinned);
  });
});
