import { afterEach, expect, it, vi } from "vite-plus/test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { Open } from "unzipper";
import { createServer, setSetting, getSetting, createScheduledTask, getScheduledTasks, exportServerPanelSettings, restoreServerPanelSettings } from "../database/init.ts";
import { runForServer } from "../utils/serverScope.ts";
import { setPanelRuntime, setServerRuntime, removeServerRuntime } from "../utils/panelRuntime.ts";
import { ServerMaintenance } from "../services/serverMaintenance.ts";
import { BackupService } from "../services/backupService.ts";
let directory: string | undefined, runtimeId: string | undefined;
afterEach(() => { if (runtimeId) removeServerRuntime(runtimeId); if (directory) fs.rmSync(directory, { recursive: true, force: true }); });
it("round-trips the world/config/accounts and only its own settings/tasks, preserving the other profile and panel settings", async () => {
  directory = fs.mkdtempSync(path.join(os.tmpdir(), "zcp-full-archive-"));
  const config = path.join(directory, "Server"), accounts = path.join(directory, "db"), world = path.join(directory, "Saves", "Multiplayer", "One");
  for (const folder of [config, accounts, world]) fs.mkdirSync(folder, { recursive: true });
  fs.writeFileSync(path.join(config, "One.ini"), "Mods=fixture\nBackupsPeriod=60\nBackupsCount=5\n");
  fs.writeFileSync(path.join(accounts, "One.db"), "PLAYER ACCOUNTS"); fs.writeFileSync(path.join(world, "map_meta.bin"), "WORLD");
  const owner = await createServer({ serverName: "One", name: "One", installPath: path.join(directory, "install"), zomboidDataPath: directory, serverConfigPath: config });
  const peer = await createServer({ serverName: "Two", name: "Two" });
  await runForServer(owner.id, async () => { await setSetting("backupMaxCount", 5); await setSetting("panelPort", 3333); await createScheduledTask("Owner save", "0 * * * *", "save"); });
  await runForServer(peer.id, async () => { await setSetting("backupMaxCount", 17); await createScheduledTask("Peer save", "30 * * * *", "save"); });
  const manager = { _serverId: owner.id, getServerProcessDetails: async () => ({ running: false, scanFailed: false }), reloadConfig: vi.fn(async () => {}) };
  const rcon = { connected: false, reloadConfig: vi.fn(async () => {}) };
  const maintenance = new ServerMaintenance(owner.id, rcon, manager, { emit: vi.fn() });
  const backup = new BackupService(maintenance); backup.setServerManager(manager); backup.setRconService(rcon);
  const scheduler = { stopAllJobs: vi.fn(), init: vi.fn(async () => {}) }, modChecker = { init: vi.fn(async () => {}) };
  setPanelRuntime({}); setServerRuntime(owner.id, { scheduler, modChecker, serverManager: manager, io: {}, maintenance }); runtimeId = owner.id;
  await runForServer(owner.id, async () => {
    const created = await backup.createBackup(); expect(created.success, created.message).toBe(true);
    const zip = await Open.file(created.backup!.path);
    expect(zip.files.some(file => /panel\.sqlite|db\.sqlite|workshop/i.test(file.path))).toBe(false);
    const manifest = JSON.parse((await zip.files.find(file => file.path === "panel-server-profile.json")!.buffer()).toString());
    expect(manifest.panel.settings.backupMaxCount).toBe(5); expect(manifest.panel.settings.panelPort).toBeUndefined(); expect(manifest.panel.tasks.map((task: any) => task.name)).toEqual(["Owner save"]);
    fs.writeFileSync(path.join(world, "map_meta.bin"), "CHANGED"); fs.writeFileSync(path.join(accounts, "One.db"), "CHANGED");
    await setSetting("backupMaxCount", 9); await createScheduledTask("Later task", "15 * * * *", "save");
    const restored = await backup.restoreBackup(created.backup!.name); expect(restored.success, restored.message).toBe(true);
    expect(fs.readFileSync(path.join(world, "map_meta.bin"), "utf8")).toBe("WORLD"); expect(fs.readFileSync(path.join(accounts, "One.db"), "utf8")).toBe("PLAYER ACCOUNTS");
    expect(await getSetting("backupMaxCount")).toBe(5); expect((await getScheduledTasks()).map(task => task.name)).toEqual(["Owner save"]); expect(await getSetting("panelPort")).toBe(3333);
    expect(scheduler.stopAllJobs).toHaveBeenCalledOnce(); expect(scheduler.init).toHaveBeenCalledOnce();
    const previous = exportServerPanelSettings();
    expect(() => restoreServerPanelSettings({ ...previous, settings: { authDisabled: true } })).toThrow("panel-level");
    expect(() => restoreServerPanelSettings({ ...previous, tasks: [{ name: "bad", cron_expression: "* * * * * *", command: "save", enabled: 1 }] })).toThrow("scheduled task");
    expect(exportServerPanelSettings()).toEqual(previous);
  });
  await runForServer(peer.id, async () => { expect(await getSetting("backupMaxCount")).toBe(17); expect((await getScheduledTasks()).map(task => task.name)).toEqual(["Peer save"]); });
});
