import { afterEach, expect, it, vi } from "vite-plus/test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createServer } from "../database/init.ts";
import { runForServer } from "../utils/serverScope.ts";
import { UpdateChecker } from "../services/updateChecker.ts";
import { clearActiveSteamOperation, steamInstallKey, getActiveSteamOperations } from "../services/activeSteamOperations.ts";
import { setPanelRuntime } from "../utils/panelRuntime.ts";
let directory: string | undefined;
afterEach(() => { getActiveSteamOperations().clear(); if (directory) fs.rmSync(directory, { recursive: true, force: true }); });
it("two concurrent requests reserve a shared Steam install once, retaining the lock through the stopped maintenance work", async () => {
  directory = fs.mkdtempSync(path.join(os.tmpdir(), "SteamCase-"));
  fs.mkdirSync(path.join(directory, "steamapps"));
  fs.writeFileSync(path.join(directory, "steamapps", "appmanifest_380870.acf"), '"buildid" "100"');
  fs.writeFileSync(path.join(directory, process.platform === "win32" ? "steamcmd.exe" : "steamcmd.sh"), "fixture");
  const server = await createServer({ serverName: "Only", installPath: directory });
  let release: (() => void) | undefined;
  const pending = new Promise<void>(resolve => { release = resolve; });
  const maintenance = { active: null, state: async () => ({ running: false }), run: vi.fn(async () => { await pending; return { success: false, deferred: true, message: "Fixture complete" }; }) };
  setPanelRuntime({});
  const checker = new UpdateChecker({ emit: vi.fn() }, { maintenance: maintenance as any });
  await runForServer(server.id, async () => {
    const results = await Promise.allSettled([checker.beginUpdate({ steamcmdPath: directory }), checker.beginUpdate({ steamcmdPath: directory })]);
    expect(results.filter(result => result.status === "fulfilled")).toHaveLength(1); expect(results.filter(result => result.status === "rejected")).toHaveLength(1);
    expect(maintenance.run).toHaveBeenCalledOnce(); expect(getActiveSteamOperations().has(steamInstallKey(directory!))).toBe(true);
    release!(); await vi.waitFor(() => expect(checker.updating).toBe(false)); expect(getActiveSteamOperations().has(steamInstallKey(directory!))).toBe(false);
  });
  clearActiveSteamOperation(steamInstallKey(directory));
});
