import { describe, expect, it, beforeEach, afterEach } from "vitest";
import fs from "fs";
import os from "os";
import path from "path";
import { createServer, setActiveServer, getActiveServer, deleteServer } from "../database/init.js";


function createResponse() {
  const response = { status: () => response, json: () => response };
  let statusCode = 200;
  let body = null;
  response.status = (code) => {
    statusCode = code;
    return response;
  };
  response.json = (payload) => {
    body = payload;
    return response;
  };
  response.getStatusCode = () => statusCode;
  response.getBody = () => body;
  return response;
}

function getRouteHandler(router, routePath, method) {
  const layer = router.stack.find(
    (entry) => entry.route?.path === routePath && entry.route.methods[method],
  );
  return layer.route.stack[layer.route.stack.length - 1].handle;
}

describe("PUT /servers/:id -- editing useUpnp actually changes the server's own .ini, not just its DB row", () => {
  let tmpRoot;
  let serverConfigPath;
  let iniPath;
  let previousActiveServerId;
  let createdServerId;

  beforeEach(async () => {
    tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "zcp-upnp-edit-"));
    serverConfigPath = path.join(tmpRoot, "data", "Server");
    fs.mkdirSync(serverConfigPath, { recursive: true });
    iniPath = path.join(serverConfigPath, "UpnpEditTest.ini");
    fs.writeFileSync(
      iniPath,
      "# Auto-generated by Zomboid Control Panel\nRCONPort=27015\nRCONPassword=x\nUPnP=true\n",
    );
    previousActiveServerId = (await getActiveServer())?.id ?? null;
    createdServerId = null;
  });

  afterEach(async () => {
    fs.rmSync(tmpRoot, { recursive: true, force: true });
    if (createdServerId != null) {
      await deleteServer(createdServerId);
      createdServerId = null;
    }
    if (previousActiveServerId != null) {
      await setActiveServer(previousActiveServerId);
    }
  });

  it("PUT with useUpnp:false actually rewrites the ini's UPnP= line, not just the DB row", async () => {
    const server = await createServer({
      name: "UpnpEditTest",
      serverName: "UpnpEditTest",
      installPath: tmpRoot,
      serverConfigPath,
      rconHost: "127.0.0.1",
      rconPort: 27015,
      rconPassword: "x",
      useUpnp: true,
    });
    createdServerId = server.id;
    await setActiveServer(server.id);

    const { default: router } = await import("../routes/servers.ts");
    const res = createResponse();
    await getRouteHandler(router, "/:id", "put")(
      { params: { id: String(server.id) }, body: { useUpnp: false }, app: { get: () => undefined } },
      res,
    );

    expect(res.getStatusCode()).toBe(200);
    const content = fs.readFileSync(iniPath, "utf-8");
    expect(content).toContain("UPnP=false");
    expect(content).not.toContain("UPnP=true");

    const body = res.getBody();
    expect(body.warnings?.some((w) => /next time this server starts/i.test(w))).toBe(true);
  });

  it("does NOT touch DefaultPort/UDPPort as a side effect of only changing useUpnp", async () => {
    fs.writeFileSync(
      iniPath,
      "# Auto-generated by Zomboid Control Panel\nDefaultPort=16261\nUDPPort=16262\nUPnP=true\n",
    );
    const server = await createServer({
      name: "UpnpEditPortTest",
      serverName: "UpnpEditTest",
      installPath: tmpRoot,
      serverConfigPath,
      rconHost: "127.0.0.1",
      rconPort: 27016,
      rconPassword: "x",
      useUpnp: true,
    });
    createdServerId = server.id;
    await setActiveServer(server.id);

    const { default: router } = await import("../routes/servers.ts");
    const res = createResponse();
    await getRouteHandler(router, "/:id", "put")(
      { params: { id: String(server.id) }, body: { useUpnp: false }, app: { get: () => undefined } },
      res,
    );

    expect(res.getStatusCode()).toBe(200);
    const content = fs.readFileSync(iniPath, "utf-8");
    expect(content).toContain("DefaultPort=16261");
    expect(content).toContain("UDPPort=16262");
    expect(content).toContain("UPnP=false");
  });

  it("warns (does not silently succeed) when the server has never booted and has no ini to apply UPnP to", async () => {
    fs.rmSync(iniPath);
    const server = await createServer({
      name: "UpnpNoIniTest",
      serverName: "UpnpEditTest",
      installPath: tmpRoot,
      serverConfigPath,
      rconHost: "127.0.0.1",
      rconPort: 27017,
      rconPassword: "x",
      useUpnp: true,
    });
    createdServerId = server.id;
    await setActiveServer(server.id);

    const { default: router } = await import("../routes/servers.ts");
    const res = createResponse();
    await getRouteHandler(router, "/:id", "put")(
      { params: { id: String(server.id) }, body: { useUpnp: false }, app: { get: () => undefined } },
      res,
    );

    expect(res.getStatusCode()).toBe(200);
    const body = res.getBody();
    expect(body.warnings?.some((w) => /UPnP/i.test(w))).toBe(true);
  });
});
