import { describe, expect, it, beforeEach, afterEach } from "vitest";
import fs from "fs";
import os from "os";
import path from "path";
import { createServer, setActiveServer, getActiveServer, deleteServer } from "../database/init.js";

// 2026-08-26, same-night follow-up to d8f7ddc: adding useUpnp to
// ALLOWED_SERVER_UPDATE_FIELDS alone would have recreated the exact bug
// being fixed, one layer over -- Dwight's audit caught this on the diff
// before it shipped. Grepped confirmed: nothing server-side ever reads a
// per-server useUpnp column back out. Persisting the field is necessary
// but not sufficient; the actual runtime toggle is the UPnP= line in the
// server's own .ini. This file proves the STRONGER property Dwight/god
// asked for: a field the user can set through the edit screen has a real
// runtime consumer, not just a database column nobody reads. A test that
// only checked persistence (like createServerFieldParity.test.js's own
// shape) would PASS on a write-only column and prove nothing -- this is
// deliberately a different, stronger check.

function createResponse() {
  const response = { status: () => response, json: () => response };
  let statusCode = 200;
  let body = null;
  response.status = (code) => {
    statusCode = code;
    return response;
  };
  response.json = (payload) => {
    body = payload;
    return response;
  };
  response.getStatusCode = () => statusCode;
  response.getBody = () => body;
  return response;
}

function getRouteHandler(router, routePath, method) {
  const layer = router.stack.find(
    (entry) => entry.route?.path === routePath && entry.route.methods[method],
  );
  return layer.route.stack[layer.route.stack.length - 1].handle;
}

describe("PUT /servers/:id -- editing useUpnp actually changes the server's own .ini, not just its DB row", () => {
  let tmpRoot;
  let serverConfigPath;
  let iniPath;
  // This file's own server becomes the shared test DB's active server (see
  // setActiveServer() calls below) -- both must be undone in afterEach, not
  // just the temp directory. Left active with a now-deleted installPath, a
  // later test anywhere in the same suite run that calls getActiveServer()
  // would inherit it: normalizeServerMemory() (database/init.js) computes
  // isRemote fresh from whether installPath currently resolves on disk, so
  // an orphaned record with its temp dir gone reads as isRemote:true to
  // every consumer, indefinitely. Confirmed as the exact cause of
  // bugfixes.test.js's intermittent "config mutation guard" failure
  // (2026-08-26) -- captured via DIAG instrumentation, DIAG_ACTIVE_SERVER
  // showing this file's "UpnpEditTest" server with isRemote:true at the
  // moment that unrelated test failed.
  let previousActiveServerId;
  let createdServerId;

  beforeEach(async () => {
    tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "zcp-upnp-edit-"));
    serverConfigPath = path.join(tmpRoot, "data", "Server");
    fs.mkdirSync(serverConfigPath, { recursive: true });
    iniPath = path.join(serverConfigPath, "UpnpEditTest.ini");
    // A server that has already booted at least once -- the scenario where
    // an operator would actually go edit this setting after the fact.
    fs.writeFileSync(
      iniPath,
      "# Auto-generated by Zomboid Control Panel\nRCONPort=27015\nRCONPassword=x\nUPnP=true\n",
    );
    previousActiveServerId = (await getActiveServer())?.id ?? null;
    createdServerId = null;
  });

  afterEach(async () => {
    fs.rmSync(tmpRoot, { recursive: true, force: true });
    if (createdServerId != null) {
      await deleteServer(createdServerId);
      createdServerId = null;
    }
    if (previousActiveServerId != null) {
      await setActiveServer(previousActiveServerId);
    }
  });

  it("PUT with useUpnp:false actually rewrites the ini's UPnP= line, not just the DB row", async () => {
    const server = await createServer({
      name: "UpnpEditTest",
      serverName: "UpnpEditTest",
      installPath: tmpRoot,
      serverConfigPath,
      rconHost: "127.0.0.1",
      rconPort: 27015,
      rconPassword: "x",
      useUpnp: true,
    });
    createdServerId = server.id;
    await setActiveServer(server.id);

    const { default: router } = await import("../routes/servers.js");
    const res = createResponse();
    await getRouteHandler(router, "/:id", "put")(
      { params: { id: String(server.id) }, body: { useUpnp: false }, app: { get: () => undefined } },
      res,
    );

    expect(res.getStatusCode()).toBe(200);
    const content = fs.readFileSync(iniPath, "utf-8");
    expect(content).toContain("UPnP=false");
    expect(content).not.toContain("UPnP=true");

    // PZ only reads the ini at its own boot -- the write above is
    // immediate, its effect on a currently-running server is not. The
    // response must say so rather than implying the change is already
    // live (2026-08-26: named explicitly after a same-night review caught
    // this as the same "confident status the app cannot back" class as the
    // two earlier fixes tonight).
    const body = res.getBody();
    expect(body.warnings?.some((w) => /next time this server starts/i.test(w))).toBe(true);
  });

  it("does NOT touch DefaultPort/UDPPort as a side effect of only changing useUpnp", async () => {
    fs.writeFileSync(
      iniPath,
      "# Auto-generated by Zomboid Control Panel\nDefaultPort=16261\nUDPPort=16262\nUPnP=true\n",
    );
    const server = await createServer({
      name: "UpnpEditPortTest",
      serverName: "UpnpEditTest",
      installPath: tmpRoot,
      serverConfigPath,
      rconHost: "127.0.0.1",
      rconPort: 27016,
      rconPassword: "x",
      useUpnp: true,
    });
    createdServerId = server.id;
    await setActiveServer(server.id);

    const { default: router } = await import("../routes/servers.js");
    const res = createResponse();
    await getRouteHandler(router, "/:id", "put")(
      { params: { id: String(server.id) }, body: { useUpnp: false }, app: { get: () => undefined } },
      res,
    );

    expect(res.getStatusCode()).toBe(200);
    const content = fs.readFileSync(iniPath, "utf-8");
    expect(content).toContain("DefaultPort=16261");
    expect(content).toContain("UDPPort=16262");
    expect(content).toContain("UPnP=false");
  });

  it("warns (does not silently succeed) when the server has never booted and has no ini to apply UPnP to", async () => {
    fs.rmSync(iniPath); // simulate a server that has never started
    const server = await createServer({
      name: "UpnpNoIniTest",
      serverName: "UpnpEditTest",
      installPath: tmpRoot,
      serverConfigPath,
      rconHost: "127.0.0.1",
      rconPort: 27017,
      rconPassword: "x",
      useUpnp: true,
    });
    createdServerId = server.id;
    await setActiveServer(server.id);

    const { default: router } = await import("../routes/servers.js");
    const res = createResponse();
    await getRouteHandler(router, "/:id", "put")(
      { params: { id: String(server.id) }, body: { useUpnp: false }, app: { get: () => undefined } },
      res,
    );

    expect(res.getStatusCode()).toBe(200);
    const body = res.getBody();
    expect(body.warnings?.some((w) => /UPnP/i.test(w))).toBe(true);
  });
});
