/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as ServerConfigRouteImport } from './routes/server-config'
import { Route as ServerSetupRouteImport } from './routes/server-setup'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorldMapRouteImport } from './routes/world-map'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerConfigRoute = ServerConfigRouteImport.update({
  id: '/server-config',
  path: '/server-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerSetupRoute = ServerSetupRouteImport.update({
  id: '/server-setup',
  path: '/server-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldMapRoute = WorldMapRouteImport.update({
  id: '/world-map',
  path: '/world-map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/backups': typeof BackupsRoute
  '/console': typeof ConsoleRoute
  '/debug': typeof DebugRoute
  '/mods': typeof ModsRoute
  '/players': typeof PlayersRoute
  '/scheduler': typeof SchedulerRoute
  '/server-config': typeof ServerConfigRoute
  '/server-setup': typeof ServerSetupRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/world-map': typeof WorldMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/backups': typeof BackupsRoute
  '/console': typeof ConsoleRoute
  '/debug': typeof DebugRoute
  '/mods': typeof ModsRoute
  '/players': typeof PlayersRoute
  '/scheduler': typeof SchedulerRoute
  '/server-config': typeof ServerConfigRoute
  '/server-setup': typeof ServerSetupRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/world-map': typeof WorldMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/backups': typeof BackupsRoute
  '/console': typeof ConsoleRoute
  '/debug': typeof DebugRoute
  '/mods': typeof ModsRoute
  '/players': typeof PlayersRoute
  '/scheduler': typeof SchedulerRoute
  '/server-config': typeof ServerConfigRoute
  '/server-setup': typeof ServerSetupRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/world-map': typeof WorldMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/backups'
    | '/console'
    | '/debug'
    | '/mods'
    | '/players'
    | '/scheduler'
    | '/server-config'
    | '/server-setup'
    | '/servers'
    | '/settings'
    | '/world-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/backups'
    | '/console'
    | '/debug'
    | '/mods'
    | '/players'
    | '/scheduler'
    | '/server-config'
    | '/server-setup'
    | '/servers'
    | '/settings'
    | '/world-map'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/backups'
    | '/console'
    | '/debug'
    | '/mods'
    | '/players'
    | '/scheduler'
    | '/server-config'
    | '/server-setup'
    | '/servers'
    | '/settings'
    | '/world-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BackupsRoute: typeof BackupsRoute
  ConsoleRoute: typeof ConsoleRoute
  DebugRoute: typeof DebugRoute
  ModsRoute: typeof ModsRoute
  PlayersRoute: typeof PlayersRoute
  SchedulerRoute: typeof SchedulerRoute
  ServerConfigRoute: typeof ServerConfigRoute
  ServerSetupRoute: typeof ServerSetupRoute
  ServersRoute: typeof ServersRoute
  SettingsRoute: typeof SettingsRoute
  WorldMapRoute: typeof WorldMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-config': {
      id: '/server-config'
      path: '/server-config'
      fullPath: '/server-config'
      preLoaderRoute: typeof ServerConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-setup': {
      id: '/server-setup'
      path: '/server-setup'
      fullPath: '/server-setup'
      preLoaderRoute: typeof ServerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-map': {
      id: '/world-map'
      path: '/world-map'
      fullPath: '/world-map'
      preLoaderRoute: typeof WorldMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BackupsRoute: BackupsRoute,
  ConsoleRoute: ConsoleRoute,
  DebugRoute: DebugRoute,
  ModsRoute: ModsRoute,
  PlayersRoute: PlayersRoute,
  SchedulerRoute: SchedulerRoute,
  ServerConfigRoute: ServerConfigRoute,
  ServerSetupRoute: ServerSetupRoute,
  ServersRoute: ServersRoute,
  SettingsRoute: SettingsRoute,
  WorldMapRoute: WorldMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
