/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as MapRouteImport } from './routes/map'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ServerSettingsRouteImport } from './routes/server-settings'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServersNewRouteImport } from './routes/servers_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerSettingsRoute = ServerSettingsRouteImport.update({
  id: '/server-settings',
  path: '/server-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersNewRoute = ServersNewRouteImport.update({
  id: '/servers_/new',
  path: '/servers/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/backups': typeof BackupsRoute
  '/config': typeof ConfigRoute
  '/console': typeof ConsoleRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/map': typeof MapRoute
  '/mods': typeof ModsRoute
  '/players': typeof PlayersRoute
  '/schedule': typeof ScheduleRoute
  '/server-settings': typeof ServerSettingsRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/servers/new': typeof ServersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/backups': typeof BackupsRoute
  '/config': typeof ConfigRoute
  '/console': typeof ConsoleRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/map': typeof MapRoute
  '/mods': typeof ModsRoute
  '/players': typeof PlayersRoute
  '/schedule': typeof ScheduleRoute
  '/server-settings': typeof ServerSettingsRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/servers/new': typeof ServersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/backups': typeof BackupsRoute
  '/config': typeof ConfigRoute
  '/console': typeof ConsoleRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/map': typeof MapRoute
  '/mods': typeof ModsRoute
  '/players': typeof PlayersRoute
  '/schedule': typeof ScheduleRoute
  '/server-settings': typeof ServerSettingsRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/servers_/new': typeof ServersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/backups'
    | '/config'
    | '/console'
    | '/diagnostics'
    | '/map'
    | '/mods'
    | '/players'
    | '/schedule'
    | '/server-settings'
    | '/servers'
    | '/settings'
    | '/servers/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/backups'
    | '/config'
    | '/console'
    | '/diagnostics'
    | '/map'
    | '/mods'
    | '/players'
    | '/schedule'
    | '/server-settings'
    | '/servers'
    | '/settings'
    | '/servers/new'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/backups'
    | '/config'
    | '/console'
    | '/diagnostics'
    | '/map'
    | '/mods'
    | '/players'
    | '/schedule'
    | '/server-settings'
    | '/servers'
    | '/settings'
    | '/servers_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BackupsRoute: typeof BackupsRoute
  ConfigRoute: typeof ConfigRoute
  ConsoleRoute: typeof ConsoleRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  MapRoute: typeof MapRoute
  ModsRoute: typeof ModsRoute
  PlayersRoute: typeof PlayersRoute
  ScheduleRoute: typeof ScheduleRoute
  ServerSettingsRoute: typeof ServerSettingsRoute
  ServersRoute: typeof ServersRoute
  SettingsRoute: typeof SettingsRoute
  ServersNewRoute: typeof ServersNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-settings': {
      id: '/server-settings'
      path: '/server-settings'
      fullPath: '/server-settings'
      preLoaderRoute: typeof ServerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers_/new': {
      id: '/servers_/new'
      path: '/servers/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof ServersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BackupsRoute: BackupsRoute,
  ConfigRoute: ConfigRoute,
  ConsoleRoute: ConsoleRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  MapRoute: MapRoute,
  ModsRoute: ModsRoute,
  PlayersRoute: PlayersRoute,
  ScheduleRoute: ScheduleRoute,
  ServerSettingsRoute: ServerSettingsRoute,
  ServersRoute: ServersRoute,
  SettingsRoute: SettingsRoute,
  ServersNewRoute: ServersNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
