import fs from "fs";
import path from "path";
import { createLogger } from "../utils/logger.ts";
import { getActiveServer } from "../database/init.ts";
import { hasIniKeyValue, setIniKeyLine } from "../utils/iniKeyWrite.ts";
import { resolveLaunchMode } from "./serverManager.ts";
import { normalizeMemoryGb } from "../utils/memory.ts";
import { withFileLock, writeFileAtomic } from "../utils/fileWriteQueue.ts";
import { sanitizeIniValue } from "../utils/sanitize.ts";
import { ErrorCode } from "../utils/errorCodes.ts";
import { isContainerized } from "../utils/dockerDetect.ts";

const log = createLogger("ServerLaunch");
const isWindows = process.platform === "win32";

type AnyRecord = Record<string, any>;

export function isFirstBootMissingAdminPassword(
  activeServer: AnyRecord | null,
) {
  if (
    !activeServer ||
    activeServer.isRemote ||
    !activeServer.serverName ||
    !activeServer.zomboidDataPath ||
    activeServer.adminPassword
  ) {
    return false;
  }
  const saveDir = path.join(
    activeServer.zomboidDataPath,
    "Saves",
    "Multiplayer",
    activeServer.serverName,
  );
  return !fs.existsSync(saveDir);
}

export function candidateIniPaths(
  serverConfigPath: string,
  zomboidDataPath: string | null,
  serverName: string,
) {
  const candidates = [];
  if (serverConfigPath) {
    candidates.push(path.join(serverConfigPath, `${serverName}.ini`));
  }
  if (zomboidDataPath) {
    candidates.push(path.join(zomboidDataPath, `${serverName}.ini`));
    candidates.push(path.join(zomboidDataPath, "servertest.ini"));
    candidates.push(path.join(zomboidDataPath, "serveroptions.ini"));
  }
  return candidates;
}

export async function ensureRconConfigured() {
  let serverConfigPathKind: "install" | "data" = "install";
  let serverConfigPath: string | null = null;
  try {
    const activeServer = await getActiveServer();
    if (!activeServer) {
      log.debug("ensureRconConfigured: No active server");
      return false;
    }

    serverConfigPathKind = activeServer.serverConfigPath ? "install" : "data";
    serverConfigPath =
      activeServer.serverConfigPath ||
      (activeServer.zomboidDataPath
        ? path.join(activeServer.zomboidDataPath, "Server")
        : null);
    const serverName = activeServer.serverName;
    const rconPassword = activeServer.rconPassword;
    const rconPort = activeServer.rconPort || 27015;

    if (!serverConfigPath || !serverName) {
      log.debug("ensureRconConfigured: Missing serverConfigPath or serverName");
      return false;
    }
    const configPath = serverConfigPath;

    if (!rconPassword) {
      log.debug("ensureRconConfigured: No RCON password configured");
      return false;
    }

    const iniPath =
      candidateIniPaths(
        serverConfigPath,
        activeServer.zomboidDataPath ?? null,
        serverName,
      ).find((candidate) => fs.existsSync(candidate)) ||
      path.join(serverConfigPath, `${serverName}.ini`);

    return await withFileLock(iniPath, async () => {
      if (!fs.existsSync(iniPath)) {
        log.info(
          `ensureRconConfigured: INI not found — pre-creating ${iniPath} with RCON settings`,
        );
        try {
          if (!fs.existsSync(configPath)) {
            fs.mkdirSync(configPath, { recursive: true });
            log.info(`Created server config directory: ${configPath}`);
          }
          const safePassword = sanitizeIniValue(rconPassword);
          const minimalIni = `# Auto-generated by Zomboid Control Panel\n# PZ will add remaining default settings on first server start\nRCONPort=${rconPort}\nRCONPassword=${safePassword}\n`;
          writeFileAtomic(iniPath, minimalIni, {
            encoding: "utf-8",
            mode: 0o600,
          });
          log.info(`Pre-created INI with RCON settings (port: ${rconPort})`);
          return true;
        } catch (createError: any) {
          if (createError.code === "EACCES") {
            const guidance = formatWritablePathError(
              serverConfigPathKind,
              configPath,
            );
            log.error(
              `Failed to pre-create INI file: ${createError.message} -- ${guidance.message}`,
            );
          } else {
            log.error(`Failed to pre-create INI file: ${createError.message}`);
          }
          return false;
        }
      }

      let content = fs.readFileSync(iniPath, "utf-8").replace(/\r\n/g, "\n");
      const hasCorrectPassword = hasIniKeyValue(
        content,
        "RCONPassword",
        rconPassword,
      );
      const hasCorrectPort = hasIniKeyValue(content, "RCONPort", rconPort);

      if (hasCorrectPassword && hasCorrectPort) {
        log.debug("ensureRconConfigured: RCON already configured correctly");
        return true;
      }

      log.info(`Auto-configuring RCON in ${iniPath}`);

      const safePassword = sanitizeIniValue(rconPassword);
      content = setIniKeyLine(content, "RCONPassword", safePassword);
      content = setIniKeyLine(content, "RCONPort", rconPort);

      writeFileAtomic(iniPath, content, { encoding: "utf-8", mode: 0o600 });
      log.info("RCON auto-configured successfully in server .ini file");
      return true;
    });
  } catch (error: any) {
    if (error.code === "EACCES" && serverConfigPath) {
      const guidance = formatWritablePathError(
        serverConfigPathKind,
        serverConfigPath,
      );
      log.error(
        `ensureRconConfigured error: ${error.message} -- ${guidance.message}`,
      );
    } else {
      log.error(`ensureRconConfigured error: ${error.message}`);
    }
    return false;
  }
}

export function sanitizeForBatch(str: any): string {
  if (!str) return "";
  return (
    String(str)
      .replace(/[\x00-\x1F\x7F]/g, "")
      // a newline here closes out the current script line early and starts a
      // new one that the supervisor then executes as its own command)
      .replace(/[&|<>^%"`;$(){}[\]!]/g, "")
      .replace(/\.\./g, "")
      .trim()
  );
}

const WRITABLE_PATH_LABELS = Object.freeze({
  install: "Installation path",
  data: "Zomboid data folder",
});

export function formatWritablePathError(
  kind: "install" | "data",
  directoryPath: string,
  platformIsWindows = isWindows,
) {
  const label = WRITABLE_PATH_LABELS[kind];
  const isContainer = !platformIsWindows && isContainerized();
  const baseMessage = `${label} is not writable: ${directoryPath}.`;

  if (isContainer) {
    return {
      message:
        `${baseMessage} Set PUID/PGID in your .env file to match the owner ` +
        `of this bind-mounted host folder (see docker-compose.yml's Quick ` +
        `Start), then recreate the container.`,
      code:
        kind === "install"
          ? ErrorCode.WRITABLE_PATH_INSTALL_CONTAINER
          : ErrorCode.WRITABLE_PATH_DATA_CONTAINER,
      params: { path: directoryPath },
    };
  }

  if (platformIsWindows) {
    return {
      message:
        `${baseMessage} The Windows account running the panel does not own ` +
        `this folder or lacks write permission -- choose a writable folder, ` +
        `grant access through Properties > Security, or run Start.bat as Administrator.`,
      code:
        kind === "install"
          ? ErrorCode.WRITABLE_PATH_INSTALL_WINDOWS
          : ErrorCode.WRITABLE_PATH_DATA_WINDOWS,
      params: { path: directoryPath },
    };
  }

  return {
    message:
      `${baseMessage} The user running the panel does not own this folder ` +
      `or lacks write permission to it -- fix it with chown/chmod, or ` +
      `choose a folder the panel can already write to.`,
    code:
      kind === "install"
        ? ErrorCode.WRITABLE_PATH_INSTALL_BAREMETAL
        : ErrorCode.WRITABLE_PATH_DATA_BAREMETAL,
    params: { path: directoryPath },
  };
}

function buildClasspathEntries() {
  return ["java/.", "java/*"];
}

export function generateStartupScripts(options: AnyRecord) {
  const {
    serverName,
    minMemory = 4,
    maxMemory = 8,
    zomboidDataPath,
    adminPassword,
    serverPort = 16261,
    useNoSteam = false,
    useDebug = false,
  } = options;

  const safeServerName = sanitizeForBatch(serverName);
  const safeAdminPassword = adminPassword
    ? sanitizeForBatch(adminPassword)
    : "";
  const safeZomboidDataPath = zomboidDataPath
    ? sanitizeForBatch(zomboidDataPath)
    : "";
  const normalizedMinMemory = normalizeMemoryGb(minMemory, 4);
  const normalizedMaxMemory = normalizeMemoryGb(maxMemory, 8);
  const softMaxMemory = Math.max(1, Math.round(normalizedMaxMemory * 0.6));

  const jvmArgs = [
    "-XX:+IgnoreUnrecognizedVMOptions",
    "-Djava.awt.headless=true",
    useNoSteam ? "-Dzomboid.steam=0" : "-Dzomboid.steam=1",
    "-Dzomboid.znetlog=1",
    "-XX:+UseZGC",
    `-XX:SoftMaxHeapSize=${softMaxMemory}g`,
    // Return freed heap to the OS in 2 minutes instead of the 5-minute default.
    "-XX:ZUncommitDelay=120",
    // JDK 25+: 8-byte object headers. PZ's heap is millions of small objects
    // (grid squares, tile properties, items), so this is a real footprint win.
    "-XX:+UseCompactObjectHeaders",
    // Scripts/tiles/item names load a lot of duplicate strings.
    "-XX:+UseStringDeduplication",
    "-XX:-CreateCoredumpOnCrash",
    "-XX:-OmitStackTraceInFastThrow",
    `-Xms${normalizedMinMemory}g`,
    `-Xmx${normalizedMaxMemory}g`,
  ];

  if (useDebug) jvmArgs.push("-Ddebug");

  const linuxJvmArgs = [
    ...jvmArgs,
    "-XX:+UseTransparentHugePages",
    "-Djava.security.egd=file:/dev/urandom",
  ];

  const gameArgs = [`-servername "${safeServerName}"`];
  if (safeZomboidDataPath) gameArgs.push(`-cachedir="${safeZomboidDataPath}"`);
  if (safeAdminPassword) gameArgs.push(`-adminpassword "${safeAdminPassword}"`);
  if (serverPort !== 16261) gameArgs.push(`-port ${serverPort}`);
  if (useNoSteam) gameArgs.push("-nosteam");

  const classpathEntries = buildClasspathEntries();

  const batchContent = `@echo off
@setlocal enableextensions
@cd /d "%~dp0"

REM =====================================================
REM Project Zomboid Server Startup Script
REM Generated by PZ Server Manager
REM Server Name: ${safeServerName}
REM Memory: ${normalizedMinMemory}GB - ${normalizedMaxMemory}GB
REM =====================================================

SET PZ_CLASSPATH=${classpathEntries.join(";")}

".\\jre64\\bin\\java.exe" ${jvmArgs.join(" ")} -Djava.library.path=natives/;natives/win64/;. -cp %PZ_CLASSPATH% zombie.network.GameServer ${gameArgs.join(" ")}

PAUSE
`;

  const shellContent = `#!/bin/bash
cd "\$(dirname "\$0")"

# =====================================================
# Project Zomboid Server Startup Script
# Generated by PZ Server Manager
# Server Name: ${safeServerName}
# Memory: ${normalizedMinMemory}GB - ${normalizedMaxMemory}GB
# =====================================================

PZ_CLASSPATH="${classpathEntries.join(":")}"

JAVA_CMD="./jre64/bin/java"
if [ ! -f "$JAVA_CMD" ]; then
  # Try common system Java locations (CentOS, Ubuntu, etc.)
  for JPATH in /usr/bin/java /usr/local/bin/java /usr/lib/jvm/jre/bin/java; do
    if [ -f "$JPATH" ]; then
      JAVA_CMD="$JPATH"
      break
    fi
  done
  if [ ! -f "$JAVA_CMD" ]; then
    JAVA_CMD="java"
  fi
fi

# Verify Java is actually available
if ! command -v "$JAVA_CMD" >/dev/null 2>&1; then
  echo "ERROR: Java not found. Install OpenJDK: sudo yum install java-17-openjdk (CentOS) or sudo apt install openjdk-17-jre (Ubuntu)"
  exit 1
fi

INSTDIR="$(dirname "$0")"
export LD_LIBRARY_PATH="\${INSTDIR}/natives/:\${INSTDIR}/natives/linux64/:\${INSTDIR}/linux64/:\${INSTDIR}:\${INSTDIR}/jre64/lib/amd64:\${INSTDIR}/jre64/lib/x86_64:/usr/lib64:\${LD_LIBRARY_PATH}"

"$JAVA_CMD" ${linuxJvmArgs.join(" ")} -Djava.library.path=natives/:natives/linux64/:linux64/:. -cp "$PZ_CLASSPATH" zombie.network.GameServer ${gameArgs.join(" ")}
`;

  return { bat: batchContent, sh: shellContent };
}

const SCRIPT_FINGERPRINT_FILE = ".pz-panel-scripts.json";

type ScriptFileSignature = {
  size: number;
  mtimeMs: number;
  ino: number;
};

function getFileSignature(filePath: string): ScriptFileSignature {
  const stat = fs.statSync(filePath);
  return { size: stat.size, mtimeMs: stat.mtimeMs, ino: stat.ino };
}

function isSameFileSignature(
  left: unknown,
  right: ScriptFileSignature,
): left is ScriptFileSignature {
  if (!left || typeof left !== "object") return false;
  const signature = left as Partial<ScriptFileSignature>;
  return (
    signature.size === right.size &&
    signature.mtimeMs === right.mtimeMs &&
    signature.ino === right.ino
  );
}

export function regenerateStartupScriptsWithBackup(
  installPath: string,
  files: Array<{ path: string; content: string }>,
) {
  const fingerprintPath = path.join(installPath, SCRIPT_FINGERPRINT_FILE);
  let fingerprints: Record<string, ScriptFileSignature> = {};
  try {
    fingerprints = JSON.parse(fs.readFileSync(fingerprintPath, "utf8"));
  } catch {
    fingerprints = {};
  }

  const backupMessages: string[] = [];
  for (const { path: filePath, content } of files) {
    const fileName = path.basename(filePath);
    let existingSignature: ScriptFileSignature | null = null;
    try {
      existingSignature = getFileSignature(filePath);
    } catch {
      existingSignature = null;
    }

    if (existingSignature !== null) {
      const knownSignature = fingerprints[fileName];
      if (!isSameFileSignature(knownSignature, existingSignature)) {
        let backupPath = `${filePath}.bak-${new Date().toISOString().replace(/[:.]/g, "-")}`;
        if (fs.existsSync(backupPath)) {
          let suffix = 2;
          while (fs.existsSync(`${backupPath}-${suffix}`)) suffix++;
          backupPath = `${backupPath}-${suffix}`;
        }
        try {
          fs.copyFileSync(filePath, backupPath);
          backupMessages.push(
            `${fileName} had content the panel didn't last write (a hand-edit, or an install from before this backup existed) -- your version was saved to ${path.basename(backupPath)} before regenerating.`,
          );
        } catch (backupError: any) {
          log.warn(
            `Could not back up ${filePath} before regenerating: ${backupError.message}`,
          );
        }
      }
    }

    try {
      writeFileAtomic(
        filePath,
        content,
        filePath.endsWith(".sh") ? { encoding: "utf8", mode: 0o750 } : "utf8",
      );
      fingerprints[fileName] = getFileSignature(filePath);
    } catch (writeError: any) {
      log.warn(`Could not write ${filePath}: ${writeError.message}`);
    }
  }

  try {
    writeFileAtomic(
      fingerprintPath,
      JSON.stringify(fingerprints, null, 2),
      "utf8",
    );
  } catch (fingerprintError: any) {
    log.warn(
      `Could not persist script fingerprint file: ${fingerprintError.message}`,
    );
  }

  return backupMessages;
}

export async function refreshLaunchTargetBeforeStart(
  activeServer: AnyRecord | null,
  { managedHandled = false }: { managedHandled?: boolean } = {},
) {
  try {
    const rconReady = await ensureRconConfigured();
    if (rconReady) {
      log.info("RCON pre-configured in INI before server start");
    } else {
      log.warn(
        "Could not pre-configure RCON — will retry during startup polling",
      );
    }
  } catch (rconError: any) {
    log.warn(`RCON pre-configuration failed: ${rconError.message}`);
  }

  let scriptBackupWarnings: string[] = [];
  const launchMode = resolveLaunchMode(activeServer);
  if (
    !managedHandled &&
    activeServer &&
    !activeServer.startCommand &&
    activeServer.installPath &&
    launchMode.mode === "custom"
  ) {
    log.info(
      `Custom launcher mode active (${launchMode.launcherPath}) — not regenerating; the panel does not manage this script.`,
    );
  } else if (
    !managedHandled &&
    activeServer &&
    !activeServer.startCommand &&
    activeServer.installPath
  ) {
    try {
      const scripts = generateStartupScripts({
        installPath: activeServer.installPath,
        serverName: activeServer.serverName,
        minMemory: activeServer.minMemory || 4,
        maxMemory: activeServer.maxMemory || 8,
        zomboidDataPath: activeServer.zomboidDataPath || "",
        adminPassword: activeServer.adminPassword || "",
        serverPort: activeServer.serverPort || 16261,
        useNoSteam: activeServer.useNoSteam || false,
        useDebug: activeServer.useDebug || false,
      });
      const batPath = path.join(
        activeServer.installPath,
        `StartServer_${activeServer.serverName}.bat`,
      );
      const shPath = path.join(
        activeServer.installPath,
        `start-server_${activeServer.serverName}.sh`,
      );
      scriptBackupWarnings = regenerateStartupScriptsWithBackup(
        activeServer.installPath,
        [
          { path: batPath, content: scripts.bat },
          { path: shPath, content: scripts.sh.replace(/\r\n/g, "\n") },
        ],
      );
      if (scriptBackupWarnings.length > 0) {
        log.warn(
          `Startup script regeneration backed up existing content: ${scriptBackupWarnings.join(" ")}`,
        );
      }
      log.info("Regenerated startup scripts with current server config");
    } catch (scriptError: any) {
      log.warn(`Could not regenerate startup scripts: ${scriptError.message}`);
    }
  }
  return { scriptBackupWarnings };
}

export async function waitForRconAfterStart({
  rconService,
  discordBot,
  io,
}: {
  rconService: any;
  discordBot: any;
  io?: { emit?: (event: string, payload: unknown) => void };
}) {
  log.info("Waiting for RCON to be ready - starting port polling...");

  await rconService.loadConfig();
  const rconHost = rconService.config.host || "127.0.0.1";
  const rconPort = rconService.config.port || 27015;
  log.info(`Monitoring TCP port ${rconHost}:${rconPort} for activity...`);

  let rconConnected = false;
  let rconConfigured = false;
  let portOpen = false;

  const maxPollAttempts = 60;
  for (let i = 0; i < maxPollAttempts; i++) {
    if (!portOpen) {
      portOpen = await rconService.checkPortOpen(rconHost, rconPort);
      if (!portOpen) {
        log.debug(
          `RCON startup: Port ${rconHost}:${rconPort} not yet open (poll ${i + 1}/${maxPollAttempts})...`,
        );
        await new Promise((resolve) => setTimeout(resolve, 5000));
        if (!rconConfigured && i % 3 === 0) {
          rconConfigured = await ensureRconConfigured();
          if (rconConfigured) {
            log.info(
              "RCON settings auto-configured in server .ini file during startup wait",
            );
          }
        }
        continue;
      }
      log.info(
        `RCON port ${rconHost}:${rconPort} is now open! Initiating connection...`,
      );
    }

    if (rconService.forceResetConnectionState) {
      rconService.forceResetConnectionState();
    }

    try {
      const connectPromise = rconService.connect();
      const timeoutPromise = new Promise((_, reject) =>
        setTimeout(
          () => reject(new Error("Connection attempt timed out after 15s")),
          15000,
        ),
      );
      await Promise.race([connectPromise, timeoutPromise]);

      if (rconService.connected) {
        log.info("RCON connected successfully after server startup");
        rconConnected = true;
        break;
      }
      log.warn(
        "RCON connected to port but authentication/handshake failed. Retrying...",
      );
      await new Promise((resolve) => setTimeout(resolve, 5000));
    } catch (error: any) {
      log.warn(`RCON connection attempt failed: ${error.message}`);
      await new Promise((resolve) => setTimeout(resolve, 5000));
    }
  }

  if (rconConnected) {
    log.info("RCON startup sequence completed - connected");
    io?.emit?.("server:status", { running: true, state: "ready" });
    discordBot
      ?.sendEventNotification?.("serverStart", {})
      ?.catch((error: any) =>
        log.debug(`Discord serverStart notification failed: ${error.message}`),
      );
  } else {
    log.warn(
      "RCON startup sequence completed - NOT connected (auto-reconnect will keep trying every 30s)",
    );
    io?.emit?.("server:status", {
      running: true,
      state: "running-not-ready",
    });
  }

  if (rconService.setServerStarting) {
    rconService.setServerStarting(false);
  } else {
    rconService.serverStarting = false;
  }
}

const FORCE_STOP_SAVE_TIMEOUT_MS = 3000;
const GRACEFUL_STOP_CONFIRMATION_TIMEOUT_MS = 5 * 60 * 1000;

export function monitorGracefulStop(
  serverManager: any,
  releaseLifecycleLock: () => void,
) {
  if (typeof serverManager?.getServerProcessDetails !== "function") {
    releaseLifecycleLock();
    return;
  }

  const deadline = Date.now() + GRACEFUL_STOP_CONFIRMATION_TIMEOUT_MS;
  const poll = async () => {
    try {
      const details = await serverManager.getServerProcessDetails();
      if (details && !details.scanFailed && details.running === false) {
        releaseLifecycleLock();
        return;
      }
    } catch (error: any) {
      log.debug(`Graceful stop confirmation failed: ${error.message}`);
    }

    if (Date.now() >= deadline) {
      log.warn(
        "Graceful stop confirmation timed out; releasing lifecycle lock",
      );
      releaseLifecycleLock();
      return;
    }

    const timer = setTimeout(() => void poll(), 1000);
    timer.unref?.();
  };

  void poll();
}

export async function attemptBoundedSaveBeforeForceStop(rconService: any) {
  if (!rconService?.connected) return "skipped";
  try {
    const saveResult = await Promise.race([
      rconService.save({ retryOnConnectionError: false }),
      new Promise((_, reject) =>
        setTimeout(
          () => reject(new Error("Force-stop save timed out")),
          FORCE_STOP_SAVE_TIMEOUT_MS,
        ),
      ),
    ]);
    return saveResult?.success ? "saved" : "failed";
  } catch {
    return "timedOut";
  }
}
